[07/09/2017 02:43:27 PM] - root - [ERROR] --> An error occurred
Traceback (most recent call last):
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 296, in <module>
    b = UserInterface(root)
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 46, in __init__
    self.root_tree.grid(row=0, column=0, sticky=NSEW)
  File "C:\Users\Avinash\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2220, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager grid inside . which already has slaves managed by pack
[07/09/2017 02:43:51 PM] - root - [ERROR] --> An error occurred
Traceback (most recent call last):
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 296, in <module>
    b = UserInterface(root)
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 46, in __init__
    self.root_tree.grid(row=0, column=0, sticky=NSEW)
  File "C:\Users\Avinash\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2220, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager grid inside . which already has slaves managed by pack
[07/09/2017 02:44:08 PM] - root - [ERROR] --> An error occurred
Traceback (most recent call last):
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 296, in <module>
    b = UserInterface(root)
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 46, in __init__
    self.root_tree.grid(row=0, column=0, sticky=NSEW)
  File "C:\Users\Avinash\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2220, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager grid inside . which already has slaves managed by pack
[07/09/2017 02:44:17 PM] - root - [ERROR] --> An error occurred
Traceback (most recent call last):
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 296, in <module>
    b = UserInterface(root)
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 46, in __init__
    self.root_tree.grid(row=0, column=0, sticky=NSEW)
  File "C:\Users\Avinash\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2220, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager grid inside . which already has slaves managed by pack
[07/09/2017 02:45:00 PM] - root - [ERROR] --> An error occurred
Traceback (most recent call last):
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 296, in <module>
    b = UserInterface(root)
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 45, in __init__
    self.root_tree.pack(expand=True, fill=BOTH, anchor=E, sticky=NSEW)
  File "C:\Users\Avinash\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2137, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad option "-sticky": must be -after, -anchor, -before, -expand, -fill, -in, -ipadx, -ipady, -padx, -pady, or -side
[07/09/2017 02:45:09 PM] - root - [ERROR] --> An error occurred
Traceback (most recent call last):
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 296, in <module>
    b = UserInterface(root)
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 45, in __init__
    self.root_tree.pack(expand=True, fill=BOTH, sticky=NSEW)
  File "C:\Users\Avinash\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2137, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad option "-sticky": must be -after, -anchor, -before, -expand, -fill, -in, -ipadx, -ipady, -padx, -pady, or -side
[07/09/2017 02:45:37 PM] - root - [ERROR] --> An error occurred
Traceback (most recent call last):
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 296, in <module>
    b = UserInterface(root)
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 45, in __init__
    self.root_tree.pack(sticky=NSEW, expand=True, fill=BOTH )
  File "C:\Users\Avinash\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2137, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad option "-sticky": must be -after, -anchor, -before, -expand, -fill, -in, -ipadx, -ipady, -padx, -pady, or -side
[07/09/2017 02:46:00 PM] - root - [ERROR] --> An error occurred
Traceback (most recent call last):
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 296, in <module>
    b = UserInterface(root)
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 45, in __init__
    self.root_tree.pack(anchor=NSEW, expand=True, fill=BOTH )
  File "C:\Users\Avinash\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2137, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad anchor "nsew": must be n, ne, e, se, s, sw, w, nw, or center
[07/09/2017 02:46:19 PM] - root - [ERROR] --> An error occurred
Traceback (most recent call last):
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 296, in <module>
    b = UserInterface(root)
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 56, in __init__
    self.root_tree.grid(sticky=N+S+E+W)
  File "C:\Users\Avinash\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2220, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager grid inside . which already has slaves managed by pack
[07/09/2017 02:56:44 PM] - root - [ERROR] --> An error occurred
Traceback (most recent call last):
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 296, in <module>
    b = UserInterface(root)
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 42, in __init__
    xscrollbar = Scrollbar(self.root_tree, orient=HORIZONTAL)
AttributeError: 'UserInterface' object has no attribute 'root_tree'
[07/09/2017 04:29:35 PM] - root - [ERROR] --> An error occurred
Traceback (most recent call last):
  File "F:/UP_2017_CS_HN_S2/COS700/Projects/DF-Research/Program/Analysis/RegSmart/Interface.py", line 315, in <module>
    root.tk.call('encoding', 'system', 'utf-16')
_tkinter.TclError: unknown encoding "utf-16"
